### ISSUE TITLE
Typing "too fast" doesn't work

### ISSUE THREAD

**Issue by FJMentz** [code-farmz/ng-otp-input#83]
Typing in an OTP at (for me) a normal rate, doesn't jump to the next block fast enough, thus losing some of the input:

https://user-images.githubusercontent.com/17801831/151492895-aad9cff1-63f6-4538-927e-1e91eb608bb8.mp4

**Comment by code-farmz** [comment]
@FJMentz  can you check it again this should be fixed in 1.8.3

**Comment by keval101** [comment]
@code-farmz I have checked in your current [DEMO ](https://code-farmz.github.io/ng-otp-input/) link but this issue is not solved yet. I tried it many times.

**Comment by ClaytonBrawley** [comment]
This is the one flaw I have found with this library but unfortunately it makes it borderline unusable. Please give an update on plans to allow faster input when fast-keying short numeric codes.

**Comment by elmartino** [comment]
this is still an issue in the current version for me. it's a no go because of this. can the debounce be tweaked?

**Comment by code-farmz** [comment]
I'm not sure what's the issue as I could not reproduce the issue. You are welcome to create a pull request if you find a fix for this.
